[package]
name = "rotoclone-zone"
version = "0.1.0"
authors = ["Steven Goldberg"]
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master", features = ["tls"] }
serde = "1.0"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"
default-features = false
features = ["tera_templates", "serve"]